### ISSUE TITLE
Secret Referencing not working?

### ISSUE THREAD

**Issue by phiilu** [Infisical/terraform-provider-infisical#25]
I've been trying to get secret referencing working using the Terraform provider. 

I have a Service Token with the scopes set to `/**` which should be able to access all the secrets. 

Next, I have two folders, `A` and `B`. 
In the folder `A` I have a secret named `FOO` with a value of `secret`.
I reference this secret in folder B like `${dev.A.FOO}`. 

![CleanShot 2023-10-30 at 01 07 59](https://github.com/Infisical/terraform-provider-infisical/assets/8149519/2e017610-0c46-4f07-a7e9-cc08201ba6c3)
![CleanShot 2023-10-30 at 01 08 21](https://github.com/Infisical/terraform-provider-infisical/assets/8149519/4880b92b-4b2a-4beb-9a84-e948add4f23d)
![CleanShot 2023-10-30 at 01 08 58](https://github.com/Infisical/terraform-provider-infisical/assets/8149519/5749613c-1688-4893-8eec-c4d92b4cc994)

However, in terraform the output of the secret is not interpolated. 

```terraform

data "infisical_secrets" "test" {
  env_slug    = "dev"
  folder_path = "/B"  
}

output "foo" {
  value = data.infisical_secrets.test.secrets
}
```

```
Outputs:

foo = tomap({
  "ANOTHER_FOO" = {
    "comment" = ""
    "secret_type" = "shared"
    "value" = "${dev.A.FOO}"
  }
})
```

Using the CLI I can verify that it works: 

```
infisical run --env=dev --path=/B -- env | grep foo
ANOTHER_FOO=secret
```

I simplified the example a bit, in my case folder `B` would be nested an additional level, but the secret referencing should work no matter the level of nesting 🤔 

In the docs, it is stated that secret referencing is working in all the native integrations. Is the terraform provider a native integration?

**Comment by maidul98** [comment]
Hey @phiilu this is because support for reference in Terraform has not yet been added. As you can see the secrets are parsed as is https://github.com/Infisical/terraform-provider-infisical/blob/main/infisical/provider/secrets_data_source.go#L130

I have marked this as a feature request

**Comment by vmatsiiako** [comment]
Secret References are now supported by Terraform Provider

**Comment by sepulworld** [comment]
I have run into the same issue with latest version of Terraform provider but using `ephemeral "infisical_secret"` instead of data source.
